### ISSUE TITLE
Related Layers software ...

### ISSUE THREAD

**Issue by johnsonjh** [shattered/dmd-layers#4]
Hello there @DrDaveD 

I'm not an expert by any means in the AT&T BLIT terminals or Layers.

I have some related code at https://github.com/johnsonjh/layers/ 

I'm not sure the value of it, or if it is something you're interested in.

**Comment by DrDaveD** [comment]
Thanks, but I don't think that's of much interest.  It is the userspace portion of layers that depends on a /dev/xt driver in the Unix kernel.   The kernel portion is the much more significant piece, and it always was a big problem to port and support that.  That's why the pseudo-tty layers took over from it.

**Comment by johnsonjh** [comment]
Thank you
